src/lib/constants/data.ts, src/lib/data.ts, src/lib/format.ts, src/lib/skyblock.d.ts, src/routes/user/[id].svelte, static/robots.txt
Make the API responses a lot easier to deal with
=> RefactorAPIResponse

src/app.d.ts, src/database/models/users.ts, src/hooks.ts, src/routes/api/refresh.ts, src/routes/login/index.svelte, src/routes/logout.svelte, src/routes/profile.svelte
Actually refreshes the login token and sets the proper cookies. As well as makes the auth flow more seamless.
=> Refine refresh token flow

src/database/database.ts, src/routes/api/link.ts, src/routes/profile.svelte, src/routes/stats/index.svelte
Allows players to link their discord account to their profile in /profile
=> WorkingLinkForm

src/components/nav.svelte, src/routes/+layout.svelte
Make it obvious when the page is loading
=> Use `navigating` store for loading indicators

src/components/nav.svelte, src/components/stats/playerinfo.svelte, src/components/stats/skillbar.svelte, src/components/stats/skills.svelte, src/lib/constants/data.ts, src/lib/format.ts, src/lib/skyblock.d.ts, src/routes/+error.svelte, src/routes/stats/[id]/[profile]/+page.svelte
Beginning work on a stats page.
=> Stats page

src/components/stats/skills.svelte, src/lib/data.ts, src/lib/format.ts, src/routes/api/player/[uuid]/+server.ts, src/routes/stats/[id]/+page.ts, src/routes/stats/[id]/[profile]/+page.svelte
Instantly load stats page with older data, and refresh it with new data reactively.
=> PresentCachedFirst

package-lock.json, package.json
Minor correction to package.json
=> Fix package name to be `elitedev`

package-lock.json, package.json, src/components/generic/dropdown.svelte, src/components/generic/tooltip.svelte
Add a couple of generic helper components
=> GenericComponents

src/components/stats/playerinfo.svelte, src/components/stats/skills.svelte, src/lib/data.ts, src/lib/format.ts, src/lib/skyblock.d.ts, src/lib/util.ts, src/routes/api/refresh/+server.ts, src/routes/stats/[id]/[profile]/+page.svelte
Add more features to player info.
=> BetterPlayerInfo

src/components/generic/playercard.svelte, src/routes/+page.svelte, src/routes/api/leaderboard/views/+server.ts
Add popular profiles to the home page
=> PopularPlayers

src/components/generic/dropdown.svelte, src/components/generic/playercard.svelte, src/components/generic/tooltip.svelte, src/components/nav.svelte, src/components/stats/playerinfo.svelte, src/routes/+page.svelte, src/routes/profile/+page.svelte, src/routes/stats/[id]/[profile]/+page.svelte, tailwind.config.cjs
Add an `xs` breakpoint size as well as responive font sizes
=> ImprovedBreakpoints

package-lock.json, package.json, src/routes/login/+page.ts, src/routes/logout/+page.ts, src/routes/profile/+page.ts, src/routes/stats/+page.ts, src/routes/stats/[id]/+page.ts, src/routes/stats/[id]/[profile]/+page.svelte, svelte.config.js
Upgrade to newest SvelteKit version, fixes throwing redirects to simplify code.
=> Upgrade-SvelteKit

src/components/nav.svelte, src/components/stats/playerinfo.svelte, src/components/stats/weight.svelte, src/database/database.ts, src/database/models/users.ts, src/lib/constants/weights.ts, src/lib/data.ts, src/lib/skyblock.d.ts, src/lib/util.ts, src/lib/weight.ts, src/routes/api/info/[uuid]/+server.ts, src/routes/api/weight/[uuid]/+server.ts, src/routes/api/weight/[uuid]/[profileId]/+server.ts, src/routes/stats/[id]/+page.ts, src/routes/stats/[id]/[profile]/+page.svelte, src/routes/stats/[id]/[profile]/+page.ts
Adds a weight page and endpoints for calculating farming weight.
=> Add Weight

src/routes/api/auth/+server.ts, src/routes/api/login/+server.ts, src/routes/api/refresh/+server.ts, src/routes/login/+page.ts
Remove discord Oauth2 email scope as it's not used and might concern users.
=> Remove email scope

src/lib/data.ts, src/lib/skyblock.d.ts
Stop using the `last_saved`/`last_save` fields because they've been removed from the API.
=> Stop using `last_saved` field

src/components/stats/collectionbar.svelte, src/components/stats/collections.svelte, src/components/stats/skillbar.svelte, src/lib/constants/crops.ts, src/lib/format.ts
Display collections/collection progress on stats page.
=> Collections

src/lib/constants/crops.ts, src/lib/constants/data.ts, src/lib/data.ts
Moves the constant object to the more correct file.
=> Move crop rename object to `/constants/crops`

src/routes/api/weight/[uuid]/[profileId]/+server.ts
=> Fix weight not loading on first load

src/components/stats/apistatus.svelte, src/lib/data.ts, src/lib/skyblock.d.ts, src/routes/stats/[id]/[profile]/+page.svelte
Closes #45 
Adds a warning when a profile doesn't have APIs enabled.
=> Api off warning

src/components/stats/minion.svelte
=> Make sure tier array is of length 12

src/components/stats/breakdown.svelte, src/lib/constants/weights.ts, src/lib/format.ts, src/routes/stats/[id]/[profile]/+page.svelte
Closes #38 
Adds a clear weight breakdown to the stats page.
=> Weight breakdown

src/components/nav.svelte, src/routes/profile/+page.svelte, src/routes/stats/[id]/[profile]/+page.svelte
Closes #56 
Add stat page metadata.
=> Stats metadata

src/components/nav.svelte, src/components/stats/playerinfo.svelte, src/database/database.ts, src/lib/constants/data.ts, src/routes/leaderboard/+page.svelte, src/routes/leaderboard/+page.ts, src/routes/leaderboard/entry.svelte
Closes #64 
Adds a leaderboard page with navigation.
=> Leaderboard

src/components/stats/collections.svelte
Fixes #66 
Adds a sort button for the order that crops are shown on profiles. Defaults to weight sort.
=> Add sort button

src/routes/+page.svelte, src/routes/+page.ts, src/routes/api/leaderboard/weight/+server.ts, src/routes/leaderboard/entry.svelte
Closes #72 
Replaces the main page grid with a leaderboard segment.
=> Main page lb

src/components/nav.svelte, src/components/stats/minion.svelte, src/components/stats/skillbar.svelte, src/routes/+layout.svelte, src/routes/+page.svelte, src/routes/info/+page.svelte, src/routes/leaderboard/+page.svelte, src/routes/stats/[id]/[profile]/+page.svelte
Closes #69 
Adds some metadata as well as fixes some issues with inconsistent formatting.
=> Formatting

package-lock.json, package.json, src/database/database.ts, src/lib/data.ts, src/lib/hypixel.ts, src/routes/api/player/[uuid]/+server.ts, src/routes/api/profiles/[uuid]/+server.ts, src/routes/api/weight/[uuid]/+server.ts, src/routes/api/weight/[uuid]/[profileId]/+server.ts
Fixes #78 
Adds a package, `limiter`, which handles throttling. As well as use new Hypixel fetch methods.
=> Rate Limits

src/components/stats/apistatus.svelte, src/components/stats/breakdown.svelte, src/components/stats/collections.svelte, src/components/stats/jacob/contest.svelte, src/components/stats/jacob/jacobinfo.svelte, src/components/stats/jacob/medals.svelte, src/components/stats/jacob/recents.svelte, src/components/stats/player/weight.svelte, src/lib/constants/crops.ts, src/lib/constants/data.ts, src/lib/data.ts, src/lib/format.ts, src/lib/skyblock.d.ts, src/routes/leaderboard/+page.svelte, src/routes/stats/[id]/[profile]/+page.svelte, tailwind.config.cjs
Closes #79 
Adds a new Jacob's data section to the stats page, along with various small fixes.
=> Jacob Data

src/components/stats/jacob/contest.svelte, src/components/stats/jacob/jacobinfo.svelte, src/components/stats/jacob/recents.svelte, src/components/stats/jacob/stats.svelte, src/routes/leaderboard/entry.svelte, src/routes/stats/[id]/[profile]/+page.svelte
Adds more general jacob stats to the page.
=> More Jacob

src/database/database.ts
Simple check null for where query.
=> Check to ensure uuid and id aren't null

src/database/database.ts, src/routes/leaderboard/+page.svelte, src/routes/leaderboard/entry.svelte, src/routes/stats/[id]/[profile]/+page.ts
Fix the new leaderboard entry formatting from breaking the `?jump=ign` leaderboard option.
=> Fix LB Jump

src/database/database.ts
Creates a function that refreshes the top 250 leaderboard players automatically in the background, 4 per minute. This comes out to the top player's data being reloaded roughly every hour.
=> Refresh Top Players

src/routes/stats/[id]/[profile]/+page.svelte
Simply display when a profile's data was last fetched on the stats page.
=> Display Last Fetched Time

src/lib/data.ts, src/routes/api/weight/[uuid]/+server.ts, src/routes/api/weight/[uuid]/[profileId]/+server.ts
Recalculate weight when new profile data is grabbed, fixes a conflict with cooldowns, and makes more sense overall.
=> Fix Weight Caching

src/database/database.ts, src/routes/leaderboard/+page.ts
Fixes #111 
Also fixes ign changes not being updated in the ign column.
=> Fix Leaderboard Jump

src/app.html, src/components/footer.svelte, src/components/nav.svelte, src/components/stats/playerinfo.svelte, src/routes/+page.svelte, src/routes/info/+page.svelte
Should fix indexing issues with following to the Discord login portal.
=> Add nofollow rel attributes to links

src/database/database.ts, src/database/leaderboards.ts, src/database/redis.ts
Make sure that the build continues even if the Redis container can't be reached.
=> Fix Build From Failing

src/components/stats/player/weight.svelte
Forgot to change an old `?jump=` to the new method.
=> Use New Jump Syntax

src/components/stats/collectionbar.svelte
Fixes #123 
Makes collection bars more responsive for mobile devices.
=> Fix Responsiveness For Mobile Devices

.env.example, README.md, docker-compose-prod.yaml, src/components/stats/collectionbar.svelte
Closes #33 
Adds actual installation instructions.
=> Document Install

README.md
Wrong link at the end of the instructions, and use a better image.
=> Correct Port

package-lock.json, package.json, src/database/leaderboards.ts, src/lib/data.ts, src/lib/face.ts, src/routes/leaderboard/[category]/[page]/[[start]]/+page.svelte, src/routes/leaderboard/[category]/[page]/[[start]]/entry.svelte
Disable the face code for now, it might need to be moved to a separate service down the line.
=> Disable Faces

src/database/leaderboards.ts
Ensure that leaderboard entries contain valid strings and numbers, hopefully stopping a current type error.
=> Hopefully Fix TypeError

src/database/leaderboards.ts
Add more type checking and error handling to Redis operations.
=> Safe Guard Redis Operations

src/components/stats/player/skyblocklevel.svelte, src/components/stats/playerinfo.svelte, src/lib/constants/levels.ts, src/lib/skyblock.d.ts, src/routes/stats/[id=id]/[profile]/+page.svelte
Display Skyblock levels on profiles. Potential for a leaderboard later.
=> Skyblock Levels

src/routes/api/leaderboard/rank/[category]/[page]/[uuid=uuid]/[[profile=uuid]]/+server.ts, src/routes/api/weight/[uuid=uuid]/+server.ts, src/routes/api/weight/[uuid=uuid]/[profile=uuid]/+server.ts
Fix weight and rank endpoints returning half-baked responses when a new user is requested.
=> Fix Endpoints With New User

src/routes/+page.svelte
Change `3,000` weight to `3,500` weight, also update server count to be 400+
=> Update Weight Required in Elite Server

src/components/stats/player/weight.svelte, src/routes/api/weight/[uuid=uuid]/+server.ts, src/routes/leaderboard/[category]/[page]/[[start]]/+page.server.ts
Fixes #154 
Also, should make the weight endpoint more resilient, it should return the correct profiles more regularly.
=> Improve Errors

src/components/+helpplease.svelte, src/routes/+page.svelte, src/routes/stats/[id=id]/[profile]/+page.svelte
=> Ask For Help

.env.example, src/routes/+page.svelte
Move the weight requirement to a .env variable for easier changes
=> Adjust Weight Requirement

src/components/nav.svelte
Might've pushed the redesign without a working search bar for small devices, fixed now.
=> Add Search Dropdown on Mobile

src/app.html, src/components/nav.svelte, src/routes/+page.svelte
Remove unused font/icon imports (oops), and hopefully improve accessibility a little.
=> Improve Page Rating

src/database/database.ts, src/routes/profile/+page.server.ts, src/routes/profile/+page.svelte
Only display discriminators if the user has one, and support linking accounts to migrated users
=> Support Migrated Discord Users

src/routes/(auth)/guild/[id=snowflake]/jacob/+page.server.ts, src/routes/(auth)/guild/[id=snowflake]/jacob/+page.svelte, src/routes/(auth)/profile/+page.server.ts
Hopefully fixes the ban participation form from removing all scores of that crop.
=> Fix Forms Again

src/routes/(auth)/guild/[id=snowflake]/jacob/+page.server.ts
Edit the correct array instead of using the wrong crop format as a key.
=> Correct The List Key Being Used

src/components/stats/apistatus.svelte, src/lib/api/api.d.ts, src/lib/api/swagger.json, src/routes/@[id=id]/[[profile]]/+page.svelte
Restores the proper API status detection. (no one pointed out that it was broken, I got away with it)
=> Use new `api` field for displaying player APIs

src/routes/event/[event=slug]/(auth)/join/+page.svelte, src/routes/event/[event=slug]/+layout.server.ts
Should actually fix the form this time.
=> Don't Redirect and use:enhance

src/routes/(auth)/guild/[id=snowflake]/events/+page.svelte, src/routes/(auth)/guild/[id=snowflake]/events/member.svelte
Adds a ban reason modal along with improved formatting on the admin page.
=> Event Member Ban Reason

src/components/stats/playerinfo.svelte
=> Use UUIDs for SkyCrypt link

src/components/items/tools/farmingtool.svelte, src/components/stats/contests/cropselect.svelte, src/components/stats/player/gamemode.svelte, src/components/stats/player/profiles.svelte, src/components/stats/playerinfo.svelte, src/components/stats/skills.svelte, src/lib/api/elite.ts, src/routes/contests/upcoming/+page.svelte, src/routes/contests/upcoming/upcoming.svelte, src/routes/server/[guild=slug]/+page.svelte
- Improves some spacing
- Fix stranded game mode display
- Fix light mode on upcoming contests page
- Fix formatting on past events list
=> Small Patches

.env.example, src/components/footer.svelte, src/routes/+page.svelte, src/routes/support/+server.ts
Add links back to the website for a new dedicated support server.
=> New Support Server

src/routes/@[id=id]/[[profile]]/contests/+page.svelte
https://elitebot.dev/@dragonsky53/Tomato/contests
skyblock years' real time is displayed a skyblock years real time ahead
=> Fix Wrong Dates on Contests Page

src/components/nav.svelte, src/components/stats/collectionbar.svelte, src/routes/browse/+page.svelte
- Put Elite Farmers on top of /browse
- Fix page title of /browse
- Fix crop frames not updating on page swap
- Disable preload of login/logout routes
=> Small Fixes

src/components/events/linebreaks.svelte, src/routes/event/[event=slug]/+page.svelte, src/routes/event/[event=slug]/eventmember.svelte, src/routes/event/[event=slug]/leaderboard/+page.svelte
Make use of the `status` field to display a green/gray dot for event member activity when an event is running.
=> Display Event Member Status

src/lib/api/api.d.ts, src/lib/api/elite.ts, src/lib/api/swagger.json, src/routes/(auth)/guild/[id=snowflake]/+page.svelte, src/routes/(auth)/guild/[id=snowflake]/pings/+page.server.ts, src/routes/(auth)/guild/[id=snowflake]/pings/+page.svelte, src/routes/contests/[year=int]/[month=int]/+page.svelte, src/routes/contests/[year=int]/[month=int]/[day=int]/+page.svelte, src/routes/contests/[year=int]/records/+page.svelte
Adds a config page for the new upcoming contests Discord ping feature.
=> Add Upcoming Contest Pings Config Page

src/components/stats/player/discord.svelte
=> Add Link To "Not Verified" Popup

src/components/nav.svelte, src/components/stats/discord/event.svelte, src/components/stats/discord/guildicon.svelte, src/components/stats/discord/serverbar.svelte, src/components/stats/discord/usericon.svelte, src/routes/(auth)/guild/[id=snowflake]/+page.svelte, src/routes/(auth)/guild/[id=snowflake]/events/+page.svelte, src/routes/(auth)/guild/[id=snowflake]/pings/+page.server.ts, src/routes/(auth)/guild/[id=snowflake]/pings/+page.svelte, src/routes/(auth)/profile/guild.svelte, src/routes/browse/+page.svelte, src/routes/event/[event=slug]/+page.svelte, src/routes/event/[event=slug]/eventmember.svelte, src/routes/event/[event=slug]/leaderboard/+page.svelte, src/routes/info/+page.svelte, src/routes/server/[guild=slug]/+page.svelte
Collection of small fixes, basically just the commit messages
=> Various Patches

src/components/header/main-nav.svelte, src/components/items/tools/fortunebreakdown.svelte, src/components/stats/contests/participation.svelte, src/components/stats/contests/recordparticipation.svelte, src/components/stats/jacob/cropstats.svelte, src/components/stats/jacob/medals.svelte, src/components/stats/minion.svelte, src/components/stats/player/discord.svelte, src/components/stats/player/gamemode.svelte, src/components/stats/player/playername.svelte, src/components/stats/player/profiles.svelte, src/components/stats/player/skyblocklevel.svelte, src/components/ui/popover/index.ts, src/components/ui/popover/popover-content.svelte, src/components/ui/popover/popover-mobile.svelte, src/components/ui/popover/popover-trigger.svelte, src/routes/(auth)/admin/+page.svelte, src/routes/(auth)/guild/[id=snowflake]/events/+page.svelte, src/routes/(auth)/guild/[id=snowflake]/jacob/jacobsettings.svelte, src/routes/(auth)/profile/minecraftAccount.svelte, src/routes/contests/upcoming/upcoming.svelte, src/routes/event/[event=slug]/eventmember.svelte
Not a perfect implementation, hopefully native support comes for this soon.
=> Fix Popovers on Mobile

src/lib/auth.ts, src/lib/utils.ts, src/routes/(auth)/@[id=id]/[profile]/graphs/+page.server.ts, src/routes/(auth)/admin/+page.server.ts, src/routes/(auth)/guild/[id=snowflake]/+layout.server.ts, src/routes/(auth)/guild/[id=snowflake]/+page.server.ts, src/routes/(auth)/guild/[id=snowflake]/events/+page.server.ts, src/routes/(auth)/guild/[id=snowflake]/jacob/+page.server.ts, src/routes/(auth)/guild/[id=snowflake]/pings/+page.server.ts, src/routes/@[id=id]/[[profile]]/+layout.server.ts, src/routes/@[id=id]/[[profile]]/+page.server.ts
Adds and uses new helper functions for auth
=> Improve Auth Checks

src/routes/(auth)/guild/[id=snowflake]/pings/+page.svelte, src/routes/@[id=id]/[[profile]]/contests/+page.svelte, src/routes/leaderboard/[category]/[[start=int]]/+page.svelte
- Fixes toggle for irl time in contests page
- Fixes decimals showing in leaderboard pagination
- Fixes wheat ping default select value
=> Various UI Fixes

src/lib/format.ts
Fixes runecrafting and social xp showing wrong goal xp number to level up.
=> Fix XP Progress For Special Skills

.env.example, src/components/header/user-dropdown.svelte, src/components/stats/badge.svelte, src/components/stats/player/profiles.svelte, src/components/stats/playerinfo.svelte, src/lib/api/api.d.ts, src/lib/api/elite.ts, src/lib/api/swagger.json, src/lib/auth.ts, src/routes/(auth)/admin/+page.server.ts, src/routes/(auth)/admin/+page.svelte, src/routes/(auth)/profile/+page.server.ts, src/routes/(auth)/profile/+page.svelte, src/routes/+layout.svelte, src/routes/@[id=id]/[[profile]]/+layout.svelte, src/routes/[catch]/+server.ts, src/routes/contests/upcoming/upcoming.svelte, src/routes/discord/+server.ts, src/routes/info/+page.server.ts, src/routes/info/+page.svelte, src/routes/info/+page.ts, src/routes/support/+server.ts
- Display earned badges on player's stats page
- Admin options to create/edit/grant/remove badges
- Manage badge visibility on profile
- Add badge list to info page
=> Add User Badges

src/lib/utils.ts, src/routes/@[id=id]/[[profile]]/+layout.server.ts, src/routes/@[id=id]/[[profile]]/charts/+page.server.ts, src/routes/@[id=id]/[[profile]]/charts/+page.svelte
Preprocess charts data when returned by form action.
=> Fix charts data processing

src/components/ui/date-picker/date-picker.svelte, src/components/ui/popover/popover-mobile.svelte, src/routes/@[id=id]/[[profile]]/charts/+page.svelte
- Date limits on charts page
- Warning for no data
=> Add limits and warning to charts

src/components/charts/crop-graph.svelte, src/components/stats/contests/cropselect.svelte, src/components/stats/contests/cropselector.svelte, src/components/stats/playerinfo.svelte, src/routes/(auth)/admin/+page.svelte, src/routes/(auth)/profile/+page.server.ts, src/routes/(auth)/profile/+page.svelte, src/routes/@[id=id]/[[profile]]/charts/+page.svelte
- Allow sorting of badges in user profile
- Small fixes
=> Badge Sorting

src/components/ui/slider/slider-simple.svelte
This fixes the rates page throwing an internal error.
=> Fix Simple Slider UI Component

package.json, pnpm-lock.yaml, src/components/items/lorebtn.svelte, src/components/rates/armorselect.svelte, src/routes/@[id=id]/[[profile]]/+layout.server.ts, src/routes/@[id=id]/[[profile]]/+page.server.ts, src/routes/@[id=id]/[[profile]]/charts/+page.server.ts, src/routes/@[id=id]/[[profile]]/contests/+page.server.ts, src/routes/@[id=id]/[[profile]]/rates/+page.svelte
Also moves chart data fetching to only the subpage to save resources.
=> Swap Armor Pieces in Rate Calculator

src/components/items/tools/farmingtool.svelte, src/components/leaderboards/entry.svelte, src/components/stats/collectionbar.svelte, src/components/stats/contests/participation.svelte, src/components/stats/minion.svelte, src/components/ui/popover/popover-content.svelte, src/components/ui/popover/popover-mobile.svelte, src/content/random.ts, src/routes/@[id=id]/[[profile]]/+page.svelte, src/routes/contests/upcoming/upcoming.svelte, src/routes/event/[event=slug]/eventmember.svelte, src/routes/info/bonustable.svelte, src/routes/info/croptable.svelte, src/routes/info/pest-table.svelte, src/routes/leaderboard/[category]/[[start=int]]/+page.svelte
Fixes a handful of reported issues with styling in places.
=> Various Style Fixes

src/lib/constants/leaderboards.ts, src/routes/(auth)/guild/[id=snowflake]/+layout.server.ts, src/routes/+page.svelte, src/routes/leaderboard/[category]/[[start=int]]/+page.svelte
- Also fixes leaderboards not being centered
=> Add Chocolate Leaderboard

src/components/stats/discord/event.svelte, src/components/stats/discord/serverbar.svelte, src/lib/api/api.d.ts, src/lib/api/elite.ts, src/lib/api/swagger.json, src/routes/(auth)/@[id=id]/[profile]/graphs/+page.server.ts, src/routes/(auth)/guild/[id=snowflake]/+layout.server.ts, src/routes/(auth)/guild/[id=snowflake]/+page.server.ts, src/routes/(auth)/guild/[id=snowflake]/+page.svelte, src/routes/(auth)/guild/[id=snowflake]/events/+page.server.ts, src/routes/(auth)/guild/[id=snowflake]/jacob/+page.svelte, src/routes/(auth)/guild/[id=snowflake]/pings/+page.svelte, src/routes/(auth)/profile/+page.server.ts, src/routes/(auth)/profile/+page.svelte, src/routes/(auth)/profile/guild.svelte, src/routes/@[id=id]/[[profile]]/charts/+page.server.ts, src/routes/browse/+page.svelte, src/routes/server/[guild=slug]/+layout.server.ts, src/routes/server/[guild=slug]/+page.svelte
- Allow setting an admin role
- Hopefully increase the stability of auth
- Improve discord role/channel dropdowns for settings
=> Improve Server Permissions

package.json, pnpm-lock.yaml, src/components/copy-to-clipboard.svelte, src/components/stats/discord/event.svelte, src/lib/api/api.d.ts, src/lib/api/elite.ts, src/lib/api/swagger.json, src/lib/utils.ts, src/routes/(auth)/+layout.server.ts, src/routes/(auth)/event/[event=slug]/join/+page.server.ts, src/routes/(auth)/event/[event=slug]/join/+page.svelte, src/routes/(auth)/guild/[id=snowflake]/events/+page.server.ts, src/routes/(auth)/guild/[id=snowflake]/events/create-event.svelte, src/routes/(auth)/profile/+page.server.ts, src/routes/event/[event=slug]/+layout.server.ts, src/routes/event/[event=slug]/+page.server.ts, src/routes/event/[event=slug]/+page.svelte, src/routes/event/[event=slug]/event-member.svelte, src/routes/event/[event=slug]/event-team.svelte, src/routes/event/[event=slug]/leaderboard/+page.svelte, src/routes/event/[event=slug]/membership/+page.server.ts, src/routes/event/[event=slug]/membership/+page.svelte, src/routes/invite/+page.server.ts, src/routes/leaderboard/[category]/[player=id]-[profile]/+page.server.ts, src/routes/server/[guild=slug]/+layout.server.ts, src/routes/server/[guild=slug]/join/+page.server.ts, src/routes/stats/+page.server.ts
Adds basic team event support.
Still missing ability to moderate teams as an event admin - coming soon:tm:
=> Add Team Events

src/routes/event/[event=slug]/+layout.server.ts, src/routes/event/[event=slug]/membership/+page.server.ts, src/routes/event/[event=slug]/membership/+page.svelte, src/routes/login/+page.server.ts, src/routes/login/callback/+server.ts
(hopefully)
Also replaces confusing name input box.
=> Fix Login Loop When Joining Event

src/components/events/profile-event-member.svelte, src/components/stats/discord/event.svelte, src/components/stats/discord/guildicon.svelte, src/components/stats/jacob/recents.svelte, src/components/ui/combobox/combo-box.svelte, src/routes/event/[event=slug]/+page.svelte, src/routes/event/[event=slug]/membership/+page.server.ts, src/routes/event/[event=slug]/membership/+page.svelte, src/routes/server/[guild=slug]/jacobentry.svelte
- Add name word selector
- Fix kick form missing `use:enhance`
- Fix grayed out text on Event component
- Remove misleading external-link icons
=> Fix/Update Event Issues

src/components/ui/combobox/combo-box.svelte, src/routes/event/[event=slug]/membership/+page.server.ts, src/routes/event/[event=slug]/membership/+page.svelte
- Allow users to clear input on third select
- Fix payload to remove extra blank input
=> Fix Two Word Team Names

src/components/events/event-member.svelte, src/components/events/event-team.svelte, src/routes/event/[event=slug]/membership/+page.svelte, src/routes/profile/settings/+page.svelte
- Fix weight style selector breaking if same style was owned from multiple purchases
- Add crown icon next to event team owner
- Order team members by score
=> Fix Weight Style Selector

src/components/events/event-data.svelte, src/components/events/event-member.svelte, src/components/ui/combobox/combo-box.svelte, src/lib/utils.ts, src/routes/(auth)/guild/[id=snowflake]/+layout.server.ts, src/routes/(auth)/guild/[id=snowflake]/events/+page.server.ts, src/routes/(auth)/guild/[id=snowflake]/jacob/+page.server.ts, src/routes/(auth)/guild/[id=snowflake]/pings/+page.server.ts, src/routes/[catch]/+server.ts, src/routes/event/[event=slug]/+page.svelte, src/routes/profile/servers/+page.svelte, src/routes/profile/settings/+page.svelte
- Format event specific weights better
- Fix guild auth check to allow admin role onto management pages
- Fix bot invite link in profile servers page
=> Clean Up Formatting For Event Weights

src/components/events/event-leaderboard.svelte, src/components/events/event-team-leaderboard.svelte, src/routes/(auth)/@[id=id]/[profile]/graphs/+page.server.ts, src/routes/event/[event=slug]/+layout.server.ts, src/routes/event/[event=slug]/+page.svelte, src/routes/event/[event=slug]/leaderboard/+page.svelte
- Swap leaderboard button on team events
- Updated meta description for event pages
=> Add Ability To View Solo Leaderboard In Team Events

package.json, pnpm-lock.yaml, src/components/charts/crop-graph.svelte, src/components/ui/date-picker/date-picker.svelte, src/routes/@[id=id]/[[profile]]/charts/+page.server.ts, src/routes/@[id=id]/[[profile]]/charts/+page.svelte
- Allow users to select a date range for charts
- Add easy back/forward buttons to date selection
- Zoom in graphs if less than 4 crops are selected
=> Improve Charts

src/components/charts/collectiongraph.svelte, src/routes/@[id=id]/[[profile]]/charts/+page.svelte
Fixes the addition of seeds data breaking charts page, for now this just means seeds are skipped entirely.
=> Fix Seeds Breaking Charts

src/components/leaderboards/entry.svelte, src/components/ui/pagination/pagination-content.svelte, src/components/ui/pagination/pagination-item.svelte, src/content/credits.ts, src/lib/stores/leaderboardName.ts, src/routes/+layout.svelte, src/routes/@[id=id]/[[profile]]/rates/+page.svelte, src/routes/leaderboard/[category]/[[start=int]]/+page.svelte
- Toggle for showing leaderboard names in entries (makes for better screenshots)
- Improve pagination layout on mobile
=> Add option to show leaderboard names in entries

src/components/jump-link.svelte, src/components/rates/category-progress.svelte, src/components/rates/farming-gear.svelte, src/components/rates/fortune-progress.svelte, src/routes/@[id=id]/[[profile]]/rates/+page.svelte
- Fixes mobile formatting of new fortune progress section
- Adds a second crop selector to rates for ease of use
- Add category fortune totals for pet/tool
- Add BPS slider
=> Fix Fortune Progress Issues

package.json, pnpm-lock.yaml, src/components/items/lorebtn.svelte, src/components/rates/item-progress.svelte, src/components/rates/tool-selector.svelte, src/components/rates/toolconfig.svelte
- Fix some tools not showing
- Update `farming-weight` package
=> Fix various issues with rates page

pnpm-lock.yaml, src/lib/api/api.d.ts, src/lib/api/elite.ts, src/lib/api/swagger.json, src/lib/constants/crops.ts, src/routes/(auth)/admin/actions/+page.server.ts, src/routes/(auth)/admin/actions/+page.svelte, src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/+page.server.ts, src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/+page.svelte
Adds form to event management page for updating event values
=> Add ability to update event weight values

package.json, pnpm-lock.yaml, src/routes/@[id=id]/[[profile]]/rates/+page.svelte
- Also moves Fermento Artifact under general fortune, with lesser tiers under their respective crops when present
=> Fix fermento artifact double counting

src/components/stats/player/profiles.svelte, src/routes/@[id=id]/[[profile]]/contests/+page.svelte
Add expand all and collapse all buttons for player contest page
[suggestion](https://discord.com/channels/1103875528479494275/1314158533620662322)
https://github.com/user-attachments/assets/88e9a109-f6b2-41cb-ad54-d30242da2a0d
=> Add expand all & collapse all buttons

package.json, pnpm-lock.yaml, src/components/items/tools/farmingtools.svelte, src/components/rates/pet-selector.svelte
- Update `farming-weight`
- Removes daedalus axe and adds new equipment
- Add hedgehog pet to rates page
=> Pesthunters update

src/components/events/event-data.svelte, src/components/events/event-member.svelte, src/components/events/event-type.svelte, src/lib/api/api.d.ts, src/lib/api/elite.ts, src/lib/api/swagger.json, src/lib/utils.ts, src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/+page.server.ts, src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/+page.svelte, src/routes/(auth)/guild/[id=snowflake]/events/+page.server.ts, src/routes/(auth)/guild/[id=snowflake]/events/+page.svelte, src/routes/(auth)/guild/[id=snowflake]/events/create-event.svelte, src/routes/+layout.svelte, src/routes/event/[event=slug]/membership/+page.svelte
- Adds support for pest events
- Adds support for collection events
=> Support pest and collection events

package.json, pnpm-lock.yaml, src/components/events/event-member.svelte, src/components/ui/accordion/accordion-trigger.svelte, src/lib/format.ts, src/routes/event/[event=slug]/+page.svelte, src/routes/event/[event=slug]/countdown.svelte, src/routes/event/[event=slug]/leaderboard/+page.svelte
- Makes the event countdown much better looking
- Adds a faq section if you scroll down on the event page
=> Improve event countdown and add faq

src/components/ui/combobox/combo-box.svelte, src/routes/event/[event=slug]/+layout.server.ts, src/routes/event/[event=slug]/+page.svelte, src/routes/event/[event=slug]/membership/+page.svelte
- Fixes team name selection being terrible and crashing the page
- Disables buttons while loading
- No longer lets you interact with joining a team / creating a team before joining the event
=> Fix issues on the membership page of team events

src/components/sidebar/favorited-links.svelte, src/components/sidebar/sidebar-link.svelte, src/components/sidebar/upcoming-events.svelte, src/lib/servercache.ts, src/lib/stores/favorites.svelte.ts, src/routes/@[id=id]/[[profile]]/nav-crumbs.svelte
Favorited links can now be edited with this PR.
- Reorder links
- Update names
- Delete links
=> Add the ability to edit and reorder favorite links

src/components/header/search-menu.svelte, src/components/sidebar/favorited-links.svelte, src/routes/event/[event=slug]/leaderboard/+page.svelte
- Fix editing favorites being active with section collapsed
- Fix event leaderboard not shrinking enough on mobile
- Maybe fix search popup breaking sometimes
=> Fix editing favorites being active with section collapsed

package.json, pnpm-lock.yaml, src/components/ui/data-table/data-table.svelte.ts, src/components/ui/data-table/flex-render.svelte, src/components/ui/data-table/index.ts, src/components/ui/data-table/render-helpers.ts, src/lib/api/api.d.ts, src/lib/api/elite.ts, src/lib/api/swagger.json, src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/+page.server.ts, src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/+page.svelte, src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/columns.ts, src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/data-table-column-header.svelte, src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/data-table-faceted-filter.svelte, src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/data-table-pagination.svelte, src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/data-table-toolbar.svelte, src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/data-table.svelte, src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/member-list.svelte, src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/member-table-actions.svelte, src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/member.svelte
Adds a fancier table for event member management instead of the previous lists.
=> Use a data-table for event member management

src/components/discord/event.svelte, src/components/events/event-member.svelte, src/components/events/event-type.svelte, src/components/ui/tooltip/tooltip-simple.svelte, src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/+page.svelte, src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/data-table-pagination.svelte, src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/member-list.svelte, src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/member-team-row.svelte, src/routes/(auth)/guild/[id=snowflake]/events/+page.svelte, src/routes/(auth)/guild/[id=snowflake]/jacob/+page.svelte, src/routes/(auth)/guild/[id=snowflake]/jacob/jacobsettings.svelte, src/routes/(auth)/guild/[id=snowflake]/pings/+page.svelte
Fixes some sizing issues with new member management table on mobile, as well as the jacob leaderboard and contest ping management pages.
=> Fix event admin page on mobile

src/components/leaderboards/entry.svelte, src/components/stats/player/gamemode.svelte, src/lib/api/api.d.ts, src/lib/api/elite.ts, src/lib/api/swagger.json, src/lib/constants/leaderboards.ts, src/lib/servercache.ts, src/routes/+page.server.ts, src/routes/+page.svelte, src/routes/api/search/+server.ts, src/routes/leaderboard/+page.server.ts, src/routes/leaderboard/+page.svelte, src/routes/leaderboard/[category]/+layout.server.ts, src/routes/leaderboard/[category]/[[start=int]]/+page.server.ts, src/routes/leaderboard/[category]/[[start=int]]/+page.svelte, src/routes/leaderboard/category.svelte
- Adds a monthly link next to leaderboards that have a monthly variant
- Uncaps leaderboards from the hardcoded 10k
- Adds profile mode icons to leaderboard entries
=> Add basic support for monthly leaderboards

src/components/discord/event.svelte, src/components/events/event-type.svelte, src/components/sidebar/upcoming-events.svelte, src/lib/api/api.d.ts, src/lib/api/elite.ts, src/lib/api/swagger.json, src/routes/browse/+page.svelte, src/routes/event/[event=slug]/leaderboard/+page.svelte
Show recently ended events on sidebar and /browse
=> Show recently ended events

src/routes/@[id=id]/[[profile]]/rates/+page.svelte
=> Add weight gain to rates

src/components/stats/player/join-elite-popup.svelte
fix uncaught promise error when checking when checking for ign from session which can be undefined
=> fix uncaught promise error

src/components/discord/guild-icon.svelte, src/components/footer/footer-pills.svelte, src/lib/api/elite.ts, src/routes/event/[event=slug]/+page.svelte
- Adds a clear component to show who is hosting a specific event
- Adds a warning telling people they need to be in the host server to join
=> Show event host server clearly

src/components/header/header.svelte, src/components/header/search-menu.svelte, src/routes/+layout.svelte, src/routes/+page.server.ts, src/routes/leaderboard/+page.svelte, src/routes/leaderboard/category.svelte
- Reorganize leaderboards page
- Adds leaderboards to search
=> Update leaderboards page + leaderboards in search

src/components/monetization/product-card.svelte, src/components/monetization/product-price.svelte, src/routes/shop/+page.svelte, tailwind.config.ts
Product cards now look much nicer on the shop page. Also adjusted the layout of the page a bit so it has better responsiveness.
=> Refresh design of product cards

src/components/ui/sidebar/context.svelte.ts, src/routes/+layout.server.ts, src/routes/+layout.svelte
Fixes sidebar showing as open then collapsing right away in new tabs (if you had it closed)
=> Fix flash of wrong sidebar state

src/components/settings/setting-list-item.svelte, src/routes/(auth)/admin/actions/+page.svelte, src/routes/(auth)/guild/[id=snowflake]/+page.svelte, src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/+page.svelte, src/routes/(auth)/guild/[id=snowflake]/events/+page.svelte, src/routes/(auth)/guild/[id=snowflake]/jacob/+page.svelte, src/routes/(auth)/guild/[id=snowflake]/pings/+page.svelte
- Fix feature checks on server pages
- Add breadcrumbs to server pages
- Improve admin actions page
=> Improve admin/server pages

src/lib/format.ts, src/lib/stores/stats.svelte.ts, src/routes/leaderboard/+page.svelte, src/routes/leaderboard/[category]/[player=id]-[[profile]]/+page.server.ts
Fixes the rank plus color you can set in Hypixel not being used on the website.
=> Fix player configured rank plus color not being used

.vscode/settings.json, package.json, pnpm-lock.yaml, src/app.css, src/components/emoji/emoji-dialog.svelte, src/components/emoji/emoji-picker.svelte, src/components/header/mode-toggle.svelte, src/components/monetization/product.svelte, src/components/rates/upgrades/data-table-pagination.svelte, src/components/sidebar/user-dropdown.svelte, src/components/stats/apistatus.svelte, src/components/stats/jacob/jacobinfo.svelte, src/components/stats/player/playername.svelte, src/components/ui/popover/popover-content.svelte, src/components/ui/switch/switch.svelte, src/lib/api/api.d.ts, src/lib/api/elite.ts, src/lib/api/swagger.json, src/lib/format.ts, src/lib/stores/stats.svelte.ts, src/routes/(auth)/admin/product/[productId]/+page.server.ts, src/routes/(auth)/admin/product/[productId]/+page.svelte, src/routes/@[id=id]/[[profile]]/fortune/cheapest-upgrades.svelte, src/routes/profile/settings/+page.server.ts, src/routes/profile/settings/+page.svelte, src/routes/shop/[sku=int]/+page.server.ts, src/routes/shop/[sku=int]/+page.svelte
- Adds new custom emoji product perk
- Support claiming free items directly
=> Add custom emoji support

src/app.css, src/components/sidebar/player-head.svelte, src/routes/leaderboard/category.svelte
- Improves the look of the /leaderboard list page
- Fixes a couple small style issues
=> Improve leaderboard list

src/components/items/formatted-text.svelte, src/components/stats/player/playername.svelte, src/lib/constants/data.ts, src/lib/format.ts, src/lib/skyblock.d.ts
Adds support for any hardcoded Hypixel "prefix" role (hopefully).
Specifically fixes TommyInnit's INNIT role, and removes the need for special handling for PIG+++
=> Support arbitrary Hypixel roles

package.json, pnpm-lock.yaml, src/lib/format.ts
- Upgrade the `farming-weight` package to 0.10.1
- Fix blank space in front of unranked players
=> Fix axed perk

src/lib/api/elite.ts, src/routes/(auth)/@[id=id]/[profile]/graphs/+page.server.ts, src/routes/@[id=id]/+layout.server.ts, src/routes/@[id=id]/[[profile]]/fortune/bazaar-rates.svelte, src/routes/@[id=id]/[[profile]]/fortune/cheapest-upgrades.svelte, src/routes/api/items/[[item]]/+server.ts, src/routes/contests/[year=int]/[month=int]/+page.server.ts, src/routes/contests/[year=int]/[month=int]/[day=int]/+page.server.ts, src/routes/event/[event=slug]/membership/+page.server.ts, src/routes/leaderboard/[category]/[[start=int]]/+page.server.ts, src/routes/leaderboard/[category]/[player=id]-[[profile]]/+page.server.ts, src/routes/profile/settings/+page.server.ts, src/routes/shop/[sku=int]/+page.server.ts
- Improves performance of fortune page slightly by debouncing the upgrades list
- Forward request headers to relevant endpoints
=> Forward request headers

src/components/items/tools/fortune-breakdown.svelte, src/components/rates/farming-gear.svelte, src/components/rates/pet-selector.svelte, src/components/rates/tool-selector.svelte, src/routes/@[id=id]/[[profile]]/fortune/+page.svelte
- Adds mosquito pet
- Improves look of fortune page slightly
=> Improve item selectors

src/lib/api/api.d.ts, src/lib/api/elite.ts, src/lib/api/swagger.json, src/lib/hooks/global.svelte.ts, src/lib/stores/ratesData.ts, src/lib/stores/stats.svelte.ts, src/routes/@[id=id]/[[profile]]/fortune/+page.server.ts, src/routes/@[id=id]/[[profile]]/fortune/rates-settings.svelte
Allows you to save the following to your account, for other users to have populate automatically
- Strength
- Community Center Upgrade
- Exported Crops
- Attribute Shards
=> Add ability to save your fortune settings to your account

.env.example, .github/workflows/website.yaml, Dockerfile, src/components/footer/footer.svelte
- Adds a deployment action for automated deployments
- Adds commit hash to footer
=> Add deploy action

src/components/header/search-menu.svelte, src/components/player-search.svelte, src/components/ui/dialog/dialog-scroll-content.svelte, src/components/ui/popover/popover-mobile.svelte, src/components/ui/tooltip/tooltip-simple.svelte, src/lib/hooks/is-hover.svelte.ts, src/routes/+layout.svelte
Improves the structure of tooltips and popovers, reduces the close delay for popovers, and resolves issues with popovers closing immediately on mobile. Adjusts modal content animation to center correctly and ensures the command dialog has a closing animation. Additionally, applies code formatting.
=> Fix tooltip and popover issues, improve modal animations

orval.config.ts, src/lib/api/client/EliteAPI.ts, src/lib/api/custom-fetch.ts, src/lib/api/schemas/WeightStyleWithDataDto.ts, src/lib/api/util/morph-api.ts
Apparently the base url is hardcoded, so I've replaced the baseUrl string with `${ELITE_API_URL}`, then imported that env variable in the morph script.
=> Fix the base url being hard coded into the orval client

src/components/footer/footer.svelte, src/routes/profile/+page.svelte, src/routes/profile/discordAccount.svelte
- Fix unlinking secondary accounts
- Don't attempt to load empty account banner
- Add legal disclaimers to footer
=> Fix unlinking secondary accounts

package.json, pnpm-lock.yaml, src/components/charts/apex.svelte, src/components/charts/collectiongraph.svelte, src/components/header/search-menu.svelte, src/lib/styles/render.ts, vite.config.ts
It's not being used enough to be included in the bundle
=> Remove apex charts

src/components/discord/guild-icon.svelte, src/components/discord/serverbar.svelte, src/components/responsive-image.svelte, src/lib/api/client/EliteAPI.ts, src/lib/api/client/EliteAPI.zod.ts, src/lib/api/schemas/ErrorResponse.ts, src/lib/api/schemas/ErrorResponseErrors.ts, src/lib/api/schemas/ImageAttachmentDto.ts, src/lib/api/schemas/ImageAttachmentDtoSources.ts, src/lib/api/schemas/ImageSourceDto.ts, src/lib/api/schemas/ProblemDetails.ts, src/lib/api/schemas/ProblemDetailsError.ts, src/lib/api/schemas/index.ts
Use new responsive images returned from the API
=> Add responsive image component
