- src/components/stats/collectionbar.svelte
- src/components/stats/collections.svelte
- src/lib/collections.ts
- src/lib/constants/crops.ts
Fixes #30 
Uses the Hypixel skyblock collections endpoint to create a new collection tier lookup system instead of relying on the player API.
> Collection tiers

- src/hooks.server.ts
- src/routes/api/refresh/+server.ts
Fixes #61 
Uses new `cookies.set()` syntax instead of adding headers to the response body manually.
> Use new cookies.set instead of adding headers

- src/components/stats/collectionbar.svelte
- src/lib/constants/crops.ts
Crop images weren't getting the correct photo position from after updating the `PROPER_CROP_NAME` object to include the simplified names as well. Using a different source now.
> Fix Crop Images

- src/lib/weight.ts
- src/routes/info/+page.svelte
- src/routes/info/croptable.svelte
Mushroom weight is calculated dynamically because of the Mooshroom Cow pet. Because Cactus and Sugar Cane are both 2 blocks per break, the cow's perk gives you twice the normal rate of mushroom drops than from other crops. To counter this, you get half the weight from mushrooms for the ratio of Cactus and Sugar Cane farmed out of the total weight, and the remainder is calculated normally.
This change is a mild nerf, and it shouldn't affect overall player weights that much overall.
> Mushroom Weight

- src/database/database.ts
- src/database/models/users.ts
- src/lib/weight.ts
Adds `crop` field to `highest.farming` field to easily get the most farmed crop of a player.
Add `cute_name` to the `/weight` api response under `profiles[id]`.
> Improve API

- src/database/database.ts
- src/routes/leaderboard/entry.svelte
- src/routes/stats/[id]/[profile]/+page.ts
Previous database query sorted the whole `farming:` field, with the addition of `crop:` this was messed up. 
The ordering now uses a correct sort by weight value, but at the cost of a slower query.
> Fix leaderboard ordering

- src/database/database.ts
- src/routes/api/leaderboard/weight/[uuid]/+server.ts
- src/routes/leaderboard/+page.ts
- src/routes/stats/[id]/[profile]/+page.ts
`/api/leaderboard/weight/[uuid]` now responds with whole leaderboard entry, this lets you get the profile where the ranking is counted.
> Provide Rank Profile

- src/database/models/users.ts
- src/lib/weight.ts
Adds the `APISettings` object to each profile in the `/weight/<uuid>` endpoint. This is useful for easily checking/displaying this data without needing to retrieve the full profile response.
> Api Access Data in Weight Info

- src/lib/data.ts
- src/lib/skyblock.d.ts
(When it exists) use the new `claimed_medal` field to skip calculating what medal was earned.
> Use New Claimed Medal Field

- src/lib/util.ts
- src/routes/stats/[id]/[profile]/+page.svelte
Stop the client from requesting a refresh of the data when a page is fetched, it's now unneeded.
> Remove Unneeded Refresh Call

- src/routes/api/profiles/[uuid]/[profileId]/+server.ts
- src/routes/stats/[id]/+page.ts
Adds a `api/profiles/[uuid]/[profileId]` endpoint, for returning a single specified profile. `profileId` can also be substituted for "selected" which will return the active profile for that user.
> Fetch Single Profile

- src/lib/constants/levels.ts
Fix level colors, the higher color was being shown for levels one below the cutoff.
> Fix Wrong Level Colors

- .env.example
- src/lib/hypixel.ts
Makes the request limit for your key to be declared in the `.env` file.
> Add Request Limit To `.env`

- src/lib/constants/weights.ts
Updated weight values from after the garden update, mathematical tool crops remain the same, with the biggest change being mushroom.
> Garden Weight Rebalance

- src/lib/constants/weights.ts
Correct cocoa weight. The cocoa chopper was mistakenly believed to give 1.2x drops, but it only gives 20 fortune.
> Correct Cocoa Weight

- src/routes/api/profiles/[uuid=uuid]/+server.ts
- src/routes/api/profiles/[uuid=uuid]/[profile]/+server.ts
The inventories field in the `/profiles` endpoint has been replaced by `null` if the `?inv=true` query parameter isn't present.
> Exclude Inventories from API Response By Default

- src/routes/api/leaderboard/rank/[category]/[page]/[uuid=uuid]/[[profile=uuid]]/+server.ts
Adds `/api/leaderboard/rank/[category]/[page]/[uuid]/(profileid)` endpoints for getting the rank of a player on a specific leaderboard.
> Add Specific Leaderboard Rank Endpoint

- src/database/database.ts
- src/database/leaderboards.ts
- src/lib/data.ts
- src/routes/api/leaderboard/rank/[category]/[page]/[uuid=uuid]/[[profile=uuid]]/+server.ts
Profiles will now be refreshed if queried via the rank endpoint. Also adds a `?showNext=true` query parameter to that endpoint to display who you're competing against.
> Refresh Profiles

- src/routes/+page.server.ts
- src/routes/api/[...catch]/+server.ts
- src/routes/api/account/[id]/+server.ts
- src/routes/api/account/discord/[id]/+server.ts
- src/routes/api/info/[uuid=uuid]/+server.ts
- src/routes/api/leaderboard/[category]/[page]/[[player]]/+server.ts
- src/routes/api/leaderboard/rank/[category]/[page]/[uuid=uuid]/[[profile=uuid]]/+server.ts
- src/routes/api/leaderboard/ranks/[uuid]/[profile]/+server.ts
- src/routes/api/link/+server.ts
- src/routes/api/player/[uuid=uuid]/+server.ts
- src/routes/api/profiles/[uuid=uuid]/+server.ts
- src/routes/api/profiles/[uuid=uuid]/[profile]/+server.ts
- src/routes/api/refresh/+server.ts
- src/routes/api/similar/[input=ign]/+server.ts
- src/routes/api/weight/[uuid=uuid]/+server.ts
- src/routes/api/weight/[uuid=uuid]/[profile=uuid]/+server.ts
- src/routes/leaderboard/+page.server.ts
- src/routes/leaderboard/[category]/[page]/[[start]]/+page.server.ts
- src/routes/profile/+page.svelte
- src/routes/stats/[id=id]/[profile]/+page.server.ts
Set a public cache control header where appropriate and changed all `return new Resonse(JSON.stringify(...))` responses to use the built-in `return json(...)` which also corrects the data type being sent.
> Set cache control and use `return json(...)`

- src/routes/api/weights/+server.ts
Adds a self explanatory `/weights` api endpoint to get the crop weights.
https://elitebot.dev/api/weights
> Add Endpoint to Get Current Crop Weights

- src/lib/constants/weights.ts
- src/routes/info/+page.svelte
Axe crops got a very mild nerf because of the Mossy Fermento Helm being better than Lantern, and Mushroom was buffed to be almost double with the Fungi cutter being fixed.
> Garden 1.5 Balance

- src/components/events/linebreaks.svelte
- src/components/leaderboards/entry.svelte
- src/components/stats/playerinfo.svelte
- src/lib/api/api.d.ts
- src/lib/api/swagger.json
- src/lib/constants/leaderboards.ts
- src/lib/format.ts
- src/routes/(auth)/event/[event=slug]/join/+page.svelte
- src/routes/+page.svelte
- src/routes/contests/+page.svelte
- src/routes/contests/[year=int]/[month=int]/+page.svelte
- src/routes/event/[event=slug]/+page.svelte
- src/routes/event/[event=slug]/leaderboard/+page.svelte
- src/routes/leaderboard/[category]/[[start=int]]/+page.server.ts
- src/routes/leaderboard/[category]/[[start=int]]/+page.svelte
- src/routes/leaderboard/[category]/[player=id]-[profile]/+page.server.ts
A bunch of small changes
- Fix rank display - fixes #195
- Add timestamps to contests and events
- Jump to position - 10 for a player on the leaderboard
- Improve main page layout
- Format Skyblock level leaderboard as "123.45" instead of "12,345"
- Adds jump to most recent contest button to /contests page
> Small Changes

- src/components/stats/contests/participation.svelte
- src/components/stats/contests/recordparticipation.svelte
- src/lib/api/api.d.ts
- src/lib/api/swagger.json
Uses the new `removed` field to show a warning for contest participations that have since been wiped/deleted.
> Show Warning For Removed Participations

- package.json
- pnpm-lock.yaml
- Fixes farming level not counting on Rancher's boots
- Adds peridot gem support when counting fortune
> Update `farming-weight` to `0.3.9`

- src/components/footer/footer.svelte
- src/components/stats/contests/singlecontest.svelte
- src/components/stats/minion.svelte
- src/content/faq.ts
- src/routes/@[id=id]/+layout.server.ts
- src/routes/[catch]/+server.ts
- src/routes/info/+page.svelte
Some small changes:
- Allow dashed uuids in stats page url (ex: https://elitebot.dev/@7da0c475-81dc-42b4-9621-18f8049147b7)
- Clarify some things on info page
- Add Elite Farmers wiki link to footer
- Improve unlocked minion tiers popup
- Add UTC timezone label to contest records
> Allow dashed uuids in stats page url

- package.json
- pnpm-lock.yaml
- src/components/external-link-button.svelte
- src/components/items/item-lore.svelte
- src/components/items/lore.svelte
- src/components/items/lorebtn.svelte
- src/components/items/tools/farmingtool.svelte
- src/components/rates/category-progress.svelte
- src/components/rates/farming-gear.svelte
- src/components/rates/fortune-progress.svelte
- src/components/rates/item-progress.svelte
- src/components/rates/pet-selector.svelte
- src/components/rates/tool-selector.svelte
- src/components/rates/toolconfig.svelte
- src/components/stats/garden/milestone-bar.svelte
- src/components/stats/progress-bar.svelte
- src/routes/@[id=id]/[[profile]]/rates/+page.svelte
Reworks the rates page to use the new `getProgress()` functions in the `farming-weight` package in order to display fortune progress bars.
> Initial Farming Fortune Display

- package.json
- pnpm-lock.yaml
- src/components/items/tools/farmingtools.svelte
- src/components/stats/contests/cropselector.svelte
- src/routes/@[id=id]/[[profile]]/+page.svelte
- src/routes/@[id=id]/[[profile]]/rates/+page.svelte
- Make second crop selector into the `#fortune` anchor, which fixes selecting a crop on mobile shifting the whole screen since the top expands.
- Update `farming-weight` package
- Decreased bundle size
- Fixes community center upgrade falsely being 50
- Hopefully fixes lotus gear being detected as Common
- Fixes daedalus axes showing 0 fortune by loading in pets
> Fix more fortune display issues

- src/components/items/tools/fortune-breakdown.svelte
Resolves: https://discord.com/channels/1103875528479494275/1314488643150155776
Fixes the incorrect color being used for maxed fortune-breakdown component (currently only used in pb score ff tag).
> Fix: Incorrect maxed fortune breakdown color

- src/components/rates/pet-selector.svelte
- src/components/stats/breakdown.svelte
- src/components/stats/contests/crop-selector.svelte
- src/components/stats/contests/cropselector.svelte
- src/components/stats/jacob/contest-list.svelte
- src/components/stats/jacob/contest.svelte
- src/components/stats/jacob/crop-medal-counts.svelte
- src/components/stats/jacob/crop-stats.svelte
- src/components/stats/jacob/cropstats.svelte
- src/components/stats/jacob/jacob-crop-stats.svelte
- src/components/stats/jacob/jacobinfo.svelte
- src/components/stats/jacob/medalcounts.svelte
- src/components/stats/jacob/recent-contests.svelte
- src/components/ui/popover/popover-content.svelte
- src/components/ui/scroll-area/scroll-area.svelte
- src/lib/api/api.d.ts
- src/lib/api/swagger.json
- src/routes/(auth)/@[id=id]/[profile]/graphs/+page.svelte
- src/routes/@[id=id]/[[profile]]/+page.svelte
- src/routes/@[id=id]/[[profile]]/charts/+page.svelte
- src/routes/@[id=id]/[[profile]]/rates/+page.svelte
- src/routes/contests/[year=int]/records/+layout.svelte
- src/routes/contests/upcoming/+page.svelte
- tailwind.config.ts
Adds a new section to the website for crop specific jacob stats. Will likely have filtering and specific leaderboards in the future.
> Add new jacob crop stats

- src/components/stats/jacob/contest-list.svelte
- src/components/stats/jacob/crop-stats.svelte
Lets you select/deselect crops in the jacob contest summary, just like how it is one the charts page
https://github.com/user-attachments/assets/513c604f-4a91-4fa7-99ea-f34e8ac6b21b
> Add selecting multiple crops in contest summary

- src/components/stats/player/profiles.svelte
adds the total weight across all profiles in the profile switcher menu
[suggestion](https://discord.com/channels/1103875528479494275/1309581884610707496)
> Add total weight across all profiles

- src/components/stats/jacob/cropstats.svelte
- src/components/stats/jacob/jacob-crop-stats.svelte
- src/components/stats/jacob/jacobinfo.svelte
links to the contest that the pb happened in the jacob pb stats
[suggestion](https://discord.com/channels/1103875528479494275/1314161502344708136)
https://github.com/user-attachments/assets/d17e163c-2808-4230-bcde-84d1345ef530
> Add link to contest in jacob pb stats

- src/components/sidebar/nav-dynamic.svelte
- src/lib/hooks/breadcrumb.svelte.ts
- src/routes/@[id=id]/[[profile]]/nav-crumbs.svelte
fixes the unnecessary capitalization of everything in the sidebar, everything is capitalized by default now, but youre able to specifically specify to keep the original text
(no it doesnt make them all lowercase thats just how sage's names are)
> Fix names in sidebar

- src/components/copy-to-clipboard.svelte
- src/components/events/team-name-selector.svelte
- src/components/ui/popover/popover-mobile.svelte
- src/components/ui/tooltip/tooltip-simple.svelte
- src/components/visible-toggle.svelte
- src/lib/api/api.d.ts
- src/lib/api/elite.ts
- src/lib/api/swagger.json
- src/lib/servercache.ts
- src/routes/(auth)/admin/+page.svelte
- src/routes/(auth)/admin/actions/+page.server.ts
- src/routes/(auth)/admin/actions/+page.svelte
- src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/+page.server.ts
- src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/+page.svelte
- src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/columns.ts
- src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/member-list.svelte
- src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/member-row.svelte
- src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/member-table-actions.svelte
- src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/member-team-row.svelte
- src/routes/(auth)/guild/[id=snowflake]/events/+page.svelte
- src/routes/(auth)/guild/[id=snowflake]/jacob/jacobsettings.svelte
- src/routes/@[id=id]/[[profile]]/charts/+page.svelte
- src/routes/event/[event=slug]/membership/+page.server.ts
- src/routes/event/[event=slug]/membership/+page.svelte
- Correct some instances of nested buttons
- Event moderators can now do the following
- Create a team for a user
- See join codes for teams
- Kick member from team
- Add a member to a team
- Delete a team
Editing a team is missing for now.
> Add team management options to event admin page

- src/routes/leaderboard/[category]/[[start=int]]/leaderboard-pagination.svelte
Fixed issue where using button to go last page of leaderboard shows as empty.
> Fixed last page leaderboard being empty

- src/components/items/tools/farmingtools.svelte
sorts tools by their approxomite weight, the only time it would really not work is if someone has an overflowed counter and it was close to 0, but usually it should be fine
| Before | After |
|--------|--------|
| ![chrome_joTWhHSmr0](https://github.com/user-attachments/assets/5574542a-295e-426c-b50d-ac8f78cf1d7b) | ![zEPJxOEISJ](https://github.com/user-attachments/assets/6c34eed6-68fc-4080-92d5-ecb7fc266788) |
> Sort tools by approximate weight

- src/hooks.server.ts
https://developer.chrome.com/blog/immutable-document-domain
it worked with just `+` instead of the `.replace()` to keep it in alphabetical order but idk if like it still should be that way or something so im jsut gonna play it safe
also idk if theres a better way to check for chrome i saw someone say do `window.chrome` but that doesnt work
> fix header warning on chrome

- package.json
- pnpm-lock.yaml
- src/routes/@[id=id]/[[profile]]/rates/+page.svelte
Fix bazaar `otherCoins` price in rates, which fixes pumpkin/melon rng drops being double counted.
> Fix bazaar `otherCoins` number in rates

- src/components/ui/sidebar/sidebar-menu-item.svelte
- src/components/ui/sidebar/sidebar-menu-sub-item.svelte
For some reason it only shows up on Chromium browsers, so removed that (again) here after the components were updated.
> Remove list dot explicitly

- src/components/events/event-member.svelte
- src/components/sidebar/player-head.svelte
- src/lib/api/api.d.ts
- src/lib/api/swagger.json
- src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/member-row.svelte
- src/routes/(auth)/guild/[id=snowflake]/event/[eventId=snowflake]/member.svelte
- src/routes/(auth)/guild/[id=snowflake]/jacob/+page.svelte
- src/routes/@[id=id]/[[profile]]/+page.svelte
- src/routes/@[id=id]/[[profile]]/nav-crumbs.svelte
- src/routes/event/[event=slug]/membership/+page.svelte
- src/routes/profile/minecraftAccount.svelte
- src/routes/server/[guild=slug]/jacobentry.svelte
Replaces all mc-heads.net use for player avatars, replacing it with the new elite face endpoint. This is probably going to be slower, but it renders hat overlays so that's cool.
> Use elite face api instead of mc-heads in a lot of places

- .github/workflows/update-api.yaml
Adds a workflow that can be triggered manually (or automatically later with `repository_dispatch`) to update the generated api client.
> Add update api workflow
